trigger:
  - main

pr:
  - main
 
pool:
    vmImage: 'ubuntu-latest'
 
steps: 
 - task: GoTool@0
   inputs:
     version: '1.13.5'
 - task: Go@0
   inputs:
     command: 'get'
     arguments: '-d'
     workingDirectory: '$(System.DefaultWorkingDirectory)'
   displayName: "Get Dependencies"
 - task: Go@0
   inputs:
     command: 'build'
     arguments: '-v'
     workingDirectory: '$(System.DefaultWorkingDirectory)'
   displayName: "Build"
 - task: Go@0
   inputs:
     command: 'get'
     arguments: '-u github.com/jstemmer/go-junit-report'
     workingDirectory: '$(System.DefaultWorkingDirectory)'
   displayName: "Get Test Dependencies"   
 - task: Bash@3
   name: "go_test"
   inputs:
     targetType: "inline"
     script: "go test -v ./... 2>&1 | $(go env GOPATH)/bin/go-junit-report | tee test_report.xml"
   displayName: "Test"
 - task: PublishTestResults@2
   condition: always()
   inputs:
     testResultsFormat: 'JUnit'
     testResultsFiles: './test_report.xml'
     failTaskOnFailedTests: true
   displayName: "Publish Test Results"
