trigger:
  - main

pr:
  - main
 
pool:
    vmImage: 'ubuntu-latest'
 
steps: 
 - task: GoTool@0
   inputs:
     version: '1.20.1'
 - task: Go@0
   inputs:
     command: 'get'
     arguments: '-d'
     workingDirectory: '$(System.DefaultWorkingDirectory)'
   displayName: "Get Dependencies"
 - task: Go@0
   inputs:
     command: 'build'
     arguments: '-v'
     workingDirectory: '$(System.DefaultWorkingDirectory)'
   displayName: "Build"
 - script: |
      export GOBIN=/usr/local/bin/     
      go install github.com/jstemmer/go-junit-report@latest
      go test -v ./... 2>&1 | go-junit-report | tee test_report.xml
   displayName: "Test"
   workingDirectory: '$(System.DefaultWorkingDirectory)'
 - task: PublishTestResults@2
   condition: always()
   inputs:
     testResultsFormat: 'JUnit'
     testResultsFiles: './test_report.xml'
     failTaskOnFailedTests: true
   displayName: "Publish Test Results"   
