trigger:
  - main

pr:
  - main
 
pool:
    vmImage: 'ubuntu-latest'
 
steps: 
 - task: GoTool@0
   inputs:
     version: '1.13.5'
 - task: Go@0
   inputs:
     command: 'get'
     arguments: '-d'
     workingDirectory: '$(System.DefaultWorkingDirectory)'
   displayName: "Get Dependencies"
 - task: Go@0
   inputs:
     command: 'build'
     arguments: '-v'
     workingDirectory: '$(System.DefaultWorkingDirectory)'
   displayName: "Build"
 - task: Go@0
   inputs:
     command: 'test'
     arguments: './... -json | tee test_result.json'
     workingDirectory: '$(System.DefaultWorkingDirectory)'
   displayName: "Test"
 - task: PublishTestResults@2
   condition: always()
   inputs:
     testResultsFormat: 'JUnit'
     testResultsFiles: 'test_result.json'
     failTaskOnFailedTests: true
   displayName: "Publish Test Results"
